version: "3"

services:
  service:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=${DB_NAME}
    env_file:
      - .env
    ports:
      - 27017:27017
